version: "3.8"

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: caddy_config
        target: /etc/caddy/Caddyfile
    volumes:
      - caddy_data:/data
      - caddy_config_data:/config
    deploy:
      replicas: 1
      restart_policy:
        condition: any

configs:
  caddy_config:
    file: ./Caddyfile  # Must be in same directory as docker-stack.yml

volumes:
  caddy_data:
  caddy_config_data:
