version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    environment:
      - N8N_HOST=n8n.yangpenting.fun
      - N8N_PORT=5678
      - WEBHOOK_URL=https://n8n.yangpenting.fun/
      - GENERIC_TIMEZONE=Asia/Jakarta
      - TZ=Asia/Jakarta
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_ENABLE_EXTERNAL_MODULES=true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - main-dev
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

volumes:
  n8n_data:

networks:
  main-dev:
    external: true
