[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               docker.*

[FILTER]
    Name                docker
    Match               docker.*
    Merge_Log           On
    Keep_Log            Off

[FILTER]
    Name                modify
    Match               docker.*
    Add                 source docker

[OUTPUT]
    Name                loki
    Match               docker.*
    Host                loki
    Port                3100
    Labels              job=docker,service=${swarm_service_name},container=${container_name},node=${host}
    LabelKeys           level,service,trace_id
